---
base_image: ubuntu:noble

labels:
  maintainer: "Maciej Rachuna <rachuna.maciej@gmail.com>"
  image_source: "https://gitlab.com/pl.rachuna-net/containers/renovate"

env:
  DEBIAN_FRONTEND: noninteractive
  TF_IN_AUTOMATION: "true"
  LANG: C.UTF-8

before_build_commands:
  ## nodejs
  - curl -fsSL https://deb.nodesource.com/setup_22.x -o nodesource_setup.sh

packages:
  - bash
  - curl
  - git
  - gnupg2
  - jq
  - libssl3
  - lsb-release
  - openssh-client
  - ca-certificates
  - gnupg
  - python3
  - python3-pip
  - unzip
  - tzdata

custom_repos:

extra_commands:
  - chmod 777 /opt/scripts
  - chmod 777 /opt/scripts/*
  - bash /tmp/nodesource_setup.sh
  - apt-get install nodejs
  - npm install -g --unsafe-perm renovate@latest
  - renovate --version

copy:
  - source: scripts/
    destination: /opt/scripts/
  - source: nodesource_setup.sh
    destination: /tmp/nodesource_setup.sh

user:
  name: nonroot
  shell: /bin/bash
  home: /home/nonroot
  chown: /opt/scripts/

entrypoint: "/opt/scripts/entrypoint.bash"
cmd: "/bin/bash"
